# Generated by Django 3.1.7 on 2021-03-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='public',
            new_name='published',
        ),
    ]
